apiVersion: "v1"
kind: "Service"
metadata:
  name: redis-sentinel
  labels:
    name: sentinel
    role: service
spec:
  ports:
    -
      port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
